packages:
  - "."
  - "docs"

minimumReleaseAge: 1440
blockExoticSubdeps: true
saveExact: true

shellEmulator: true
nodeVersion: 24.0.0
engineStrict: true
optimisticRepeatInstall: true
verifyDepsBeforeRun: true

allowBuilds:
  dprint: true
  esbuild: true

onlyBuiltDependencies:
  - dprint
  - esbuild
